-- [SYS] 20250402

CREATE USER survey IDENTIFIED BY 1234;
GRANT CREATE SESSION TO survey;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO survey;
ALTER USER survey DEFAULT TABLESPACE users QUOTA UNLIMITED ON users;

GRANT CREATE SEQUENCE TO survey;